<Project Sdk="Microsoft.NET.Sdk.Worker">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>dotnet-FaturaHatirlatici.Bot-714b701f-beb0-425a-a77b-a62988cad9eb</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="10.0.12">
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.Extensions.Hosting" Version="10.0.12" />
    <PackageReference Include="Rask.SQLite.Browser" Version="0.23.0" />
    <PackageReference Include="Telegram.Bot" Version="22.10.3.1" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\FaturaHatirlatici.Business\FaturaHatirlatici.Business.csproj" />
  </ItemGroup>
</Project>
